//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public int idModelo { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public int MontoRealCompra { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
